/**
 * @file event_id.hpp
 * @brief Defines the event identifier domain value object.
 */

#pragma once

#include <compare>
#include <string>

namespace haven::domain {

/**
 * @brief Identifies a domain event and its corresponding outbox message.
 *
 * Event identifiers are generated by Haven and remain stable across outbox
 * publication, Kafka delivery, retries, and consumer deduplication.
 */
class EventId final {
public:
    /**
     * @brief Constructs an event identifier.
     *
     * @param value Opaque event identifier value.
     *
     * @throws std::invalid_argument when the supplied value is empty.
     */
    explicit EventId(std::string value);

    /**
     * @brief Returns the underlying opaque identifier value.
     *
     * @return Reference to the stored identifier.
     */
    [[nodiscard]] const std::string& value() const noexcept;

    auto operator<=>(const EventId&) const = default;

private:
    std::string value_;
};

}  // namespace haven::domain