/**
 * @file reservation_id.hpp
 * @brief Defines the reservation identifier domain value object.
 */

#pragma once

#include <compare>
#include <string>

namespace haven::domain {

/**
 * @brief Identifies a reservation aggregate within an organization.
 *
 * Reservation identifiers are generated by Haven and treated as opaque values.
 * Tenant context remains separate and must be supplied to repository operations.
 */
class ReservationId final {
public:
    /**
     * @brief Constructs a reservation identifier.
     *
     * @param value Opaque reservation identifier value.
     *
     * @throws std::invalid_argument when the supplied value is empty.
     */
    explicit ReservationId(std::string value);

    /**
     * @brief Returns the underlying opaque identifier value.
     *
     * @return Reference to the stored identifier.
     */
    [[nodiscard]] const std::string& value() const noexcept;

    auto operator<=>(const ReservationId&) const = default;

private:
    std::string value_;
};

}  // namespace haven::domain